// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pstblhrfbhxcobfoulzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdGJsaHJmYmh4Y29iZm91bHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NDQwMDQsImV4cCI6MjA3NDMyMDAwNH0.MGyTVTOM025s2HTGhMw3PBkqc9Ss53lTrhWuDO3AA8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});